---
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    service: backend-service
    app: backend-app
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      targetPort: 8080
      port: 8080
  selector:
    name: backend-pod
    app: backend-app
---

#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: backend-service
#  labels:
#    app: backendApp
#    name: backend-service
#spec:
#  type: ClusterIP
#  ports:
#    - targetPort: 8080
#      port: 8080
#      protocol: tcp
#  selector:
#    app: myBackend
#    name: back-end
#---
#
